version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "back"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "front"
    schedule:
      interval: "weekly"
    reviewers:
      - "jugurta"