# This is the Semantic Release configuration file. It is responsible for defining the release process for the project.
# The configuration includes the branch to release from, the preset to use, the tag format, and the repository URL.
branches: "main"
preset: "angular"
tagFormat: "${version}"
repositoryUrl: "https://github.com/jao-consulting/taxSmart.git"

# The plugins section defines the plugins to use for the release process.
plugins:
  - "@semantic-release/commit-analyzer" # Analyzes commit messages to determine the type of changes in the codebase.
  - "@semantic-release/release-notes-generator" # Generates release notes based on the commit messages.
  - "@semantic-release/changelog" # Updates the changelog file based on the release notes.
  - "@semantic-release/exec" # Executes custom shell commands.

# The analyzeCommits section defines the rules for analyzing commit messages.
analyzeCommits:
  - path: "@semantic-release/commit-analyzer"
    parserOpts:
      noteKeywords:
        - "BREAKING CHANGE"
        - "BREAKING CHANGES"
    releaseRules:
      - breaking: true
        release: "major"
      - type: "docs"
        release: false
      - type: "ci"
        release: false
      - type: "chore"
        release: "patch"
      - type: "feat"
        release: "patch"
      - type: "fix"
        release: "patch"
      - type: "refactor"
        release: "patch"
      - type: "breaking"
        release: "major"

# The generateNotes section defines the rules for generating release notes.
generateNotes:
  - path: "@semantic-release/release-notes-generator"
    writerOpts:
      groupBy: "type"
      commitGroupsSort:
        - "feat"
        - "perf"
        - "fix"
      commitsSort: "header"
    types:
      - type: "feat"
      - section: "Features"
      - type: "fix"
      - section: "Bug Fixes"
      - type: "docs"
      - hidden: true
      - type: "doc"
      - hidden: true
      - type: "style"
      - hidden: true
      - type: "refactor"
      - hidden: true
      - type: "perf"
      - hidden: true
      - type: "test"
      - hidden: true
    presetConfig: true

# The prepare section defines the steps to prepare for a release.
prepare:
  - path: "@semantic-release/exec"
    prepareCmd: "./.github/scripts/prepare-release.sh ${nextRelease.version}" # The command to run to prepare for a release.
  - path: "@semantic-release/git"
    assets:
      - "CHANGELOG.md"
      - "**/package.json"
      - "**/package-lock.json"
      - "**/pom.xml"
    message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}" # The commit message for the release commit.

# The publish section defines the steps to publish a release.
publish:
  - path: "@semantic-release/github" # Publishes the release to GitHub.