name: Backend Quality Check

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_call:
  workflow_dispatch:


jobs:
  backend-run-unit-tests:
    name: Run Back-End unit tests
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          echo "Running unit tests"
  backend-run-integration-tests:
    name: Run Back-End integration tests
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run integration tests
        run: |
          echo "Running integration tests"