name: Backend Quality Check

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches:
      - main
    paths:
      - 'back/**'
  workflow_call:
  workflow_dispatch:


jobs:
  backend-run-unit-tests:
    if: '! github.event.pull_request.draft'
    name: Run Back-End unit tests
    runs-on:
      - ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Java Unit Tests
        uses: ./.github/actions/java-cmd
        with:
          working-directory: back
          distribution: 'temurin'
          java-version: '21'
          java-cmd: mvn --batch-mode verify

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: front
          fail_ci_if_error: true

  backend-run-integration-tests:
    if: '! github.event.pull_request.draft'
    name: Run Back-End integration tests
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Java Integration Tests
        uses: ./.github/actions/java-cmd
        with:
          working-directory: back
          distribution: 'temurin'
          java-version: '21'
          java-cmd: mvn --batch-mode -DskipTests install  && mvn failsafe:integration-test