name: Build Back-End

on:
  release:
    types: [ created ]
  workflow_dispatch:
  workflow_call:

jobs:
  build-backend:
    name: Build Back-End
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Building Back
        run: |
          echo "Building Back-End"
