name: Build Front-End

on:
  release:
    types: [ created ]
  workflow_dispatch:
  workflow_call:

jobs:
  build-frontend:
    name: Build Back-End
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Building Front
        run: |
          echo "Building Front-End"
