name: Frontend Quality Check

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_call:
  workflow_dispatch:

jobs:
  frontend-run-unit-tests:
    name: Run Front-End unit tests
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          echo "Running frontend unit tests

