name: Frontend Quality Check

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches:
      - main
    paths:
      - 'front/**'
  workflow_call:
  workflow_dispatch:

jobs:
  frontend-run-unit-tests:
    if: '! github.event.pull_request.draft'
    name: Run Front-End unit tests
    runs-on:
      - ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Node Tests
        uses: ./.github/actions/node-cmd
        with:
          working-directory: front
          node-version: 20
          node-install-cmd: npm ci
          node-cmd: npm run test:coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: front
          fail_ci_if_error: true
