# This is the Scan & Detect Secrets workflow. It is responsible for scanning the codebase and detecting any secrets.
name: Scan & Detect Secrets

# This workflow is triggered on pull request events to the main branch.
on:
  pull_request:
    branches:
      - main # The branch that the pull request events must be on to trigger this workflow.
    types: [ opened, reopened, synchronize, ready_for_review ] # The types of pull request events that trigger this workflow.

# The jobs that this workflow runs.
jobs:
  # This job is responsible for scanning the codebase and detecting any secrets.
  scan-detect-secrets:
    if: '! github.event.pull_request.draft' # This job is skipped if the pull request is a draft.
    name: Scan & Detect Secrets
    runs-on:
      - ubuntu-latest # The type of runner that this job will run on.
    steps:
      # This step checks out the repository.
      - name: Checkout
        uses: actions/checkout@v4

      # This step runs the detect secrets scan.
      - name: 🕵️‍♀️ detect-secrets
        uses: reviewdog/action-detect-secrets@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # The GitHub token is used for authentication.
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' ||  'github-check' }} # The reporter to use for the scan results.
          fail_on_error: true # This option causes the job to fail if an error is detected.
          level: error # The level of issues to report.